controllers/PageController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Pages;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


/**
 * PageController implements the CRUD actions for Pages model.
 */
class PageController extends MainController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Lists all Pages models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Pages::find()->where(['user_id' => Yii::$app->getUser()->getId()]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pages model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionV($url)
    {
        if (Yii::$app->getUser()->isGuest) {
            $model = Pages::findOne(['link' => $url]);
        } else {
            $model = Pages::findOne(['link' => $url, 'user_id' => Yii::$app->getUser()->getId()]);
        }


        if (!$model) {
            throw new NotFoundHttpException();
        }
        Yii::$app->view->registerMetaTag([
            'name' => 'description',
            'content' => $model->meta_description
        ]);
        Yii::$app->view->registerMetaTag([
            'name' => 'keywords',
            'content' => $model->meta_keys
        ]);
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Pages model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }
        $model = new Pages();
        $model->user_id = Yii::$app->getUser()->getId();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['v', 'url' => $model->link]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pages model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['v', 'url' => $model->link]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pages model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if (Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pages model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pages the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pages::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/page/create.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

// kcfinder options
// http://kcfinder.sunhater.com/install#dynamic
$kcfOptions = array_merge(\iutbay\yii2kcfinder\KCFinder::$kcfDefaultOptions, [
    'uploadURL' => Yii::getAlias('@web') . '/upload',
    'access' => [
        'files' => [
            'upload' => true,
            'delete' => false,
            'copy' => false,
            'move' => false,
            'rename' => false,
        ],
        'dirs' => [
            'create' => true,
            'delete' => false,
            'rename' => false,
        ],
    ],
]);

// Set kcfinder session options
Yii::$app->session->set('KCFINDER', $kcfOptions);
?>
<div class="page-create">

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->errorSummary($model); ?>
    <?= Html::activeHiddenInput($model, 'user_id'); ?>
    <?= $form->field($model, 'title') ?>
    <?= $form->field($model, 'link') ?>
    <?= $form->field($model, 'meta_description') ?>
    <?= $form->field($model, 'meta_keys') ?>
    <?= $form->field($model, 'body')->widget(\app\components\CKEditor::className(), [
        'options' => [
            'rows' => 6,
            'toolbarGroups' => [
                ['name' => 'undo'],
                ['name' => 'basicstyles', 'groups' => ['basicstyles', 'cleanup']],
                ['name' => 'colors'],
                ['name' => 'links', 'groups' => ['links', 'insert']],
                ['name' => 'others', 'groups' => ['others', 'about']],

                ['name' => 'pbckcode']
            ]
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Mentés', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

views/page/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Oldalak';
?>
<div class="pages-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Oldal létrehozása', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            'title',
            'link',
            [
                'header' => 'Műveletek',
                'contentOptions' => ['class' => 'text-center actions-cell'],
                'class' => 'yii\grid\ActionColumn',
                'template' => '{v} {update} {delete}',
                'buttons' => [
                    'v' => function ($url, $model, $key) {
                        return Html::a(Html::encode("megtekintés"), (Url::toRoute(['page/v', 'url' => $model->link])),
                            ['class' => 'btn btn-success',]);
                    },
                    'update' => function ($url, $model, $key) {
                        return Html::a(Html::encode("szerkesztés"), $url, ['class' => 'btn btn-primary',]);
                    },
                    'delete' => function ($url, $model, $key) {
                        return Html::a('Törlés', $url, [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => 'Biztos hogy törölni akarja az elemet',
                                'method' => 'post',
                            ],
                        ]);
                    },
                ],
            ],
        ],
    ]); ?>


</div>

views/page/update.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

// kcfinder options
// http://kcfinder.sunhater.com/install#dynamic
$kcfOptions = array_merge(\iutbay\yii2kcfinder\KCFinder::$kcfDefaultOptions, [
    'uploadURL' => Yii::getAlias('@web') . '/upload',
    'access' => [
        'files' => [
            'upload' => true,
            'delete' => false,
            'copy' => false,
            'move' => false,
            'rename' => false,
        ],
        'dirs' => [
            'create' => true,
            'delete' => false,
            'rename' => false,
        ],
    ],
]);

// Set kcfinder session options
Yii::$app->session->set('KCFINDER', $kcfOptions);
?>
<div class="page-create">

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->errorSummary($model); ?>
    <?= Html::activeHiddenInput($model, 'user_id'); ?>
    <?= $form->field($model, 'title') ?>
    <?= $form->field($model, 'link') ?>
    <?= $form->field($model, 'meta_description') ?>
    <?= $form->field($model, 'meta_keys') ?>
    <?= $form->field($model, 'body')->widget(\app\components\CKEditor::className(), [
        'options' => [
            'rows' => 6,
            'toolbarGroups' => [
                ['name' => 'undo'],
                ['name' => 'basicstyles', 'groups' => ['basicstyles', 'cleanup']],
                ['name' => 'colors'],
                ['name' => 'links', 'groups' => ['links', 'insert']],
                ['name' => 'others', 'groups' => ['others', 'about']],

                ['name' => 'pbckcode']
            ]
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Mentés', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

views/page/view.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pages */

$this->title = $model->title;

?>

<div>
    <h1>
        <?php
        echo Html::decode($model->title);
        ?>
    </h1>
    <?php
    echo Html::decode($model->body);
    ?>
</div>